//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovMonitor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Filter Audio Reminders.
        /// </summary>
        internal static string AirFilterAudioReminders {
            get {
                return ResourceManager.GetString("AirFilterAudioReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Token.
        /// </summary>
        internal static string APIToken {
            get {
                return ResourceManager.GetString("APIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically delete taken screenshots after raid.
        /// </summary>
        internal static string AutomaticallyDeleteScreenshotsAfterRaid {
            get {
                return ResourceManager.GetString("AutomaticallyDeleteScreenshotsAfterRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection.
        /// </summary>
        internal static string DataCollection {
            get {
                return ResourceManager.GetString("DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don't change this unless you really know what you're doing..
        /// </summary>
        internal static string DontChangeThisUnlessYouReallyKnowWhatYoureDoing {
            get {
                return ResourceManager.GetString("DontChangeThisUnlessYouReallyKnowWhatYoureDoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get A Token.
        /// </summary>
        internal static string GetAToken {
            get {
                return ResourceManager.GetString("GetAToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup.
        /// </summary>
        internal static string InitialSetup {
            get {
                return ResourceManager.GetString("InitialSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Folder.
        /// </summary>
        internal static string LogsFolder {
            get {
                return ResourceManager.GetString("LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map to use for offline raids.
        /// </summary>
        internal static string MapToUseForOfflineRaids {
            get {
                return ResourceManager.GetString("MapToUseForOfflineRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Found Audio Notification.
        /// </summary>
        internal static string MatchFoundAudioNotification {
            get {
                return ResourceManager.GetString("MatchFoundAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to System Tray.
        /// </summary>
        internal static string MinimizeToSystemTray {
            get {
                return ResourceManager.GetString("MinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications playback device.
        /// </summary>
        internal static string NotificationsPlaybackDevice {
            get {
                return ResourceManager.GetString("NotificationsPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Map.
        /// </summary>
        internal static string OfflineMap {
            get {
                return ResourceManager.GetString("OfflineMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Item Reminder Audio Notification.
        /// </summary>
        internal static string QuestItemReminderAudioNotification {
            get {
                return ResourceManager.GetString("QuestItemReminderAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Starting Audio Notification.
        /// </summary>
        internal static string RaidStartingAudioNotification {
            get {
                return ResourceManager.GetString("RaidStartingAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Logs.
        /// </summary>
        internal static string RawLogs {
            get {
                return ResourceManager.GetString("RawLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Past Logs.
        /// </summary>
        internal static string ReadPastLogs {
            get {
                return ResourceManager.GetString("ReadPastLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote ID.
        /// </summary>
        internal static string RemoteID {
            get {
                return ResourceManager.GetString("RemoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Tasks Audio Reminder.
        /// </summary>
        internal static string RestartTasksAudioReminder {
            get {
                return ResourceManager.GetString("RestartTasksAudioReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runthrough Period Audio Reminder.
        /// </summary>
        internal static string RunthroughPeriodAudioReminder {
            get {
                return ResourceManager.GetString("RunthroughPeriodAudioReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runthrough Time (HH:MM:SS).
        /// </summary>
        internal static string RunthroughTime {
            get {
                return ResourceManager.GetString("RunthroughTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav Cooldown Reminders.
        /// </summary>
        internal static string ScavCooldownReminders {
            get {
                return ResourceManager.GetString("ScavCooldownReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav Karma.
        /// </summary>
        internal static string ScavKarma {
            get {
                return ResourceManager.GetString("ScavKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Tarkov.dev Splash Logo.
        /// </summary>
        internal static string SkipTarkovDevSplashLogo {
            get {
                return ResourceManager.GetString("SkipTarkovDevSplashLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tarkov Monitor Minimized.
        /// </summary>
        internal static string StartTarkovMonitorMinimized {
            get {
                return ResourceManager.GetString("StartTarkovMonitorMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on Top.
        /// </summary>
        internal static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Queue Time Data.
        /// </summary>
        internal static string SubmitQueueTimeData {
            get {
                return ResourceManager.GetString("SubmitQueueTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tarkov.dev map on position update (via screenshot).
        /// </summary>
        internal static string SwitchToTarkovDevMapOnPositionUpdate {
            get {
                return ResourceManager.GetString("SwitchToTarkovDevMapOnPositionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tarkov.dev map on raid load.
        /// </summary>
        internal static string SwitchToTarkovDevMapOnRaidLoad {
            get {
                return ResourceManager.GetString("SwitchToTarkovDevMapOnRaidLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarkovTracker.
        /// </summary>
        internal static string TarkovTracker {
            get {
                return ResourceManager.GetString("TarkovTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov Tracker Service.
        /// </summary>
        internal static string TarkovTrackerService {
            get {
                return ResourceManager.GetString("TarkovTrackerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov Tracker service to use.
        /// </summary>
        internal static string TarkovTrackerServiceHelperText {
            get {
                return ResourceManager.GetString("TarkovTrackerServiceHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov.dev Website Remote.
        /// </summary>
        internal static string TarkovDevWebsiteRemote {
            get {
                return ResourceManager.GetString("TarkovDevWebsiteRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Token.
        /// </summary>
        internal static string TestToken {
            get {
                return ResourceManager.GetString("TestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        internal static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Behavior.
        /// </summary>
        internal static string WindowBehavior {
            get {
                return ResourceManager.GetString("WindowBehavior", resourceCulture);
            }
        }
    }
}