//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovMonitor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Filter Audio Reminders.
        /// </summary>
        internal static string AirFilterAudioReminders {
            get {
                return ResourceManager.GetString("AirFilterAudioReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Token.
        /// </summary>
        internal static string APIToken {
            get {
                return ResourceManager.GetString("APIToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all data? This cannot be undone..
        /// </summary>
        internal static string AreYouSureYouWantToClearAllData {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToClearAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically delete taken screenshots after raid.
        /// </summary>
        internal static string AutomaticallyDeleteScreenshotsAfterRaid {
            get {
                return ResourceManager.GetString("AutomaticallyDeleteScreenshotsAfterRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the starting point from which to read logs.
        /// </summary>
        internal static string ChooseStartingPointHelperText {
            get {
                return ResourceManager.GetString("ChooseStartingPointHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data.
        /// </summary>
        internal static string ClearData {
            get {
                return ResourceManager.GetString("ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Escape From Tarkov installation location, or no logs exist..
        /// </summary>
        internal static string CouldNotFindEFTInstallation {
            get {
                return ResourceManager.GetString("CouldNotFindEFTInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile.
        /// </summary>
        internal static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Air Filter Off Sound.
        /// </summary>
        internal static string CustomAirFilterOffSound {
            get {
                return ResourceManager.GetString("CustomAirFilterOffSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Air Filter On Sound.
        /// </summary>
        internal static string CustomAirFilterOnSound {
            get {
                return ResourceManager.GetString("CustomAirFilterOnSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Log Data.
        /// </summary>
        internal static string CustomLogData {
            get {
                return ResourceManager.GetString("CustomLogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Match Found Sound.
        /// </summary>
        internal static string CustomMatchFoundSound {
            get {
                return ResourceManager.GetString("CustomMatchFoundSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Raid Starting Sound.
        /// </summary>
        internal static string CustomRaidStartingSound {
            get {
                return ResourceManager.GetString("CustomRaidStartingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Restart Tasks Sound.
        /// </summary>
        internal static string CustomRestartTasksSound {
            get {
                return ResourceManager.GetString("CustomRestartTasksSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Runthrough Period Sound.
        /// </summary>
        internal static string CustomRunthroughPeriodSound {
            get {
                return ResourceManager.GetString("CustomRunthroughPeriodSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Scav Cooldown Sound.
        /// </summary>
        internal static string CustomScavCooldownSound {
            get {
                return ResourceManager.GetString("CustomScavCooldownSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection.
        /// </summary>
        internal static string DataCollection {
            get {
                return ResourceManager.GetString("DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t change this unless you really know what you&apos;re doing..
        /// </summary>
        internal static string DontChangeThisUnlessYouReallyKnowWhatYoureDoing {
            get {
                return ResourceManager.GetString("DontChangeThisUnlessYouReallyKnowWhatYoureDoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flea Market Sale.
        /// </summary>
        internal static string FleaMarketSale {
            get {
                return ResourceManager.GetString("FleaMarketSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flea Market Sales.
        /// </summary>
        internal static string FleaMarketSales {
            get {
                return ResourceManager.GetString("FleaMarketSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get A Token.
        /// </summary>
        internal static string GetAToken {
            get {
                return ResourceManager.GetString("GetAToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to update progress for a different profile, activate that profile in the game..
        /// </summary>
        internal static string IfYouWantToUpdateProgressForDifferentProfile {
            get {
                return ResourceManager.GetString("IfYouWantToUpdateProgressForDifferentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup.
        /// </summary>
        internal static string InitialSetup {
            get {
                return ResourceManager.GetString("InitialSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Folder.
        /// </summary>
        internal static string LogsFolder {
            get {
                return ResourceManager.GetString("LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map to use for offline raids.
        /// </summary>
        internal static string MapToUseForOfflineRaids {
            get {
                return ResourceManager.GetString("MapToUseForOfflineRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Found Audio Notification.
        /// </summary>
        internal static string MatchFoundAudioNotification {
            get {
                return ResourceManager.GetString("MatchFoundAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to System Tray.
        /// </summary>
        internal static string MinimizeToSystemTray {
            get {
                return ResourceManager.GetString("MinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications playback device.
        /// </summary>
        internal static string NotificationsPlaybackDevice {
            get {
                return ResourceManager.GetString("NotificationsPlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Map.
        /// </summary>
        internal static string OfflineMap {
            get {
                return ResourceManager.GetString("OfflineMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        internal static string OpenLogsFolder {
            get {
                return ResourceManager.GetString("OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Item Reminder Audio Notification.
        /// </summary>
        internal static string QuestItemReminderAudioNotification {
            get {
                return ResourceManager.GetString("QuestItemReminderAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids.
        /// </summary>
        internal static string Raids {
            get {
                return ResourceManager.GetString("Raids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Starting Audio Notification.
        /// </summary>
        internal static string RaidStartingAudioNotification {
            get {
                return ResourceManager.GetString("RaidStartingAudioNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Logs.
        /// </summary>
        internal static string RawLogs {
            get {
                return ResourceManager.GetString("RawLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Past Logs.
        /// </summary>
        internal static string ReadPastLogs {
            get {
                return ResourceManager.GetString("ReadPastLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Previous Logs.
        /// </summary>
        internal static string ReadPreviousLogs {
            get {
                return ResourceManager.GetString("ReadPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read previous logs.
        /// </summary>
        internal static string ReadPreviousLogsLabel {
            get {
                return ResourceManager.GetString("ReadPreviousLogsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote ID.
        /// </summary>
        internal static string RemoteID {
            get {
                return ResourceManager.GetString("RemoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Tasks Audio Reminder.
        /// </summary>
        internal static string RestartTasksAudioReminder {
            get {
                return ResourceManager.GetString("RestartTasksAudioReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved {0} items, {1} maps, {2} traders, {3} tasks, and {4} hideout stations from tarkov.dev.
        /// </summary>
        internal static string RetrievedDataFromTarkovDev {
            get {
                return ResourceManager.GetString("RetrievedDataFromTarkovDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved {0} level {1} {2} progress from Tarkov Tracker.
        /// </summary>
        internal static string RetrievedDataFromTarkovTracker {
            get {
                return ResourceManager.GetString("RetrievedDataFromTarkovTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runthrough Period.
        /// </summary>
        internal static string RunthroughPeriod {
            get {
                return ResourceManager.GetString("RunthroughPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runthrough Period Audio Reminder.
        /// </summary>
        internal static string RunthroughPeriodAudioReminder {
            get {
                return ResourceManager.GetString("RunthroughPeriodAudioReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runthrough Time (HH:MM:SS).
        /// </summary>
        internal static string RunthroughTime {
            get {
                return ResourceManager.GetString("RunthroughTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav Cooldown.
        /// </summary>
        internal static string ScavCooldown {
            get {
                return ResourceManager.GetString("ScavCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav Cooldown Reminders.
        /// </summary>
        internal static string ScavCooldownReminders {
            get {
                return ResourceManager.GetString("ScavCooldownReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scav Karma.
        /// </summary>
        internal static string ScavKarma {
            get {
                return ResourceManager.GetString("ScavKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a starting point to read previous logs and update your quest progress. All logs from that point forward for the same will be read and that cumulative progress will be synced to Tarkov Tracker..
        /// </summary>
        internal static string SelectStartingPointDescription {
            get {
                return ResourceManager.GetString("SelectStartingPointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Tarkov.dev Splash Logo.
        /// </summary>
        internal static string SkipTarkovDevSplashLogo {
            get {
                return ResourceManager.GetString("SkipTarkovDevSplashLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tarkov Monitor Minimized.
        /// </summary>
        internal static string StartTarkovMonitorMinimized {
            get {
                return ResourceManager.GetString("StartTarkovMonitorMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on Top.
        /// </summary>
        internal static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Queue Time Data.
        /// </summary>
        internal static string SubmitQueueTimeData {
            get {
                return ResourceManager.GetString("SubmitQueueTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tarkov.dev map on position update (via screenshot).
        /// </summary>
        internal static string SwitchToTarkovDevMapOnPositionUpdate {
            get {
                return ResourceManager.GetString("SwitchToTarkovDevMapOnPositionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tarkov.dev map on raid load.
        /// </summary>
        internal static string SwitchToTarkovDevMapOnRaidLoad {
            get {
                return ResourceManager.GetString("SwitchToTarkovDevMapOnRaidLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov.dev Website Remote.
        /// </summary>
        internal static string TarkovDevWebsiteRemote {
            get {
                return ResourceManager.GetString("TarkovDevWebsiteRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov Monitor.
        /// </summary>
        internal static string TarkovMonitor {
            get {
                return ResourceManager.GetString("TarkovMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarkovTracker.
        /// </summary>
        internal static string TarkovTracker {
            get {
                return ResourceManager.GetString("TarkovTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov Tracker Service.
        /// </summary>
        internal static string TarkovTrackerService {
            get {
                return ResourceManager.GetString("TarkovTrackerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov Tracker service to use.
        /// </summary>
        internal static string TarkovTrackerServiceHelperText {
            get {
                return ResourceManager.GetString("TarkovTrackerServiceHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Token.
        /// </summary>
        internal static string TestToken {
            get {
                return ResourceManager.GetString("TestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any messages yet..
        /// </summary>
        internal static string ThereArentAnyMessagesYet {
            get {
                return ResourceManager.GetString("ThereArentAnyMessagesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In Raid.
        /// </summary>
        internal static string TimeInRaid {
            get {
                return ResourceManager.GetString("TimeInRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        internal static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To automatically track task progress, set your Tarkov Tracker token in Settings.
        /// </summary>
        internal static string ToAutomaticallyTrackTaskProgress {
            get {
                return ResourceManager.GetString("ToAutomaticallyTrackTaskProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} profile.
        /// </summary>
        internal static string UsingProfile {
            get {
                return ResourceManager.GetString("UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You can mess up your Tarkov Tracker saved quest progress if you pick an invalid starting date, so proceed with caution..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Behavior.
        /// </summary>
        internal static string WindowBehavior {
            get {
                return ResourceManager.GetString("WindowBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t in a group or have party members yet..
        /// </summary>
        internal static string YouArentInAGroupOrHavePartyMembersYet {
            get {
                return ResourceManager.GetString("YouArentInAGroupOrHavePartyMembersYet", resourceCulture);
            }
        }
    }
}
